jacky:
    command_prefix: ?
    commands:
        - { class: Jacky\Commands\SayCommand, advanced: true }
        - { class: Jacky\Commands\SpotifyCommand, advanced: true }
        - { class: Jacky\Commands\ImgurCommand, advanced: true }
        - { class: Jacky\Commands\CarCommand, advanced: true }
    description:  Un bot qui apporte de la joie à votre chan
    redis:
        host: 127.0.0.1
